services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-test-task-app
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: backend-test-task-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: mysql:8.0
    container_name: backend-test-task-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_task
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: backend-test-task-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app

volumes:
  redis_data:
  db_data:
